//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loginasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string correo { get; set; }
        public string hash { get; set; }
        public string helper { get; set; }
        public string nombre_completo { get; set; }
        public string pais { get; set; }
        public string direccion { get; set; }
        public string foto_path { get; set; }
        public int id { get; set; }
    }
}
